config/routes.rb
Rails.application.routes.draw do
  get '/answer', to: 'coaching#answer'
  get '/ask', to: 'coaching#ask'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/coaching_controller.rb
class CoachingController < ApplicationController
  def answer
    @question = params[:query]

  end

  def ask

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coaching_helper.rb
module CoachingHelper
end

app/views/coaching/answer.html.erb
<div class="container">
  <div class="answers">
    <blockquote class="blockquote">
      <p class="mb-0"><%= @question %></p>
      <footer class="blockquote-footer"><cite title="Source Title">You</cite></footer>
    </blockquote>
    <% if @question.include?("?") %>
    <p>Silly question, get dressed and go to work!</p>
    <% elsif @question == 'I am going to work right now!' %>
    <p>...</p>
    <% else %>
    <blockquote class="blockquote">
      <p class="mb-0">I don't care, get dressed and go to work!</p>
      <footer class="blockquote-footer"><cite title="Source Title">Your coach</cite></footer>
    </blockquote>
    <% end %>
  </div>
  <div class="answers">
    <%= link_to "Ask a new question", ask_path %>
  </div>
</div>

app/views/coaching/ask.html.erb
<div class="container">
    <form action="<%=answer_path%>" class="form-inline">
      <!-- add bootstrap form here -->
      <div class="item form-group">
        <label >Speak to your coach</label>
        <input class="form-control" type="text" id="question" name="query" placeholder="what time is it?">
        <button type="submit" class="btn btn-primary">Go on!</button>
      </div>
    </form>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>